name: payexecution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  # GCP_REGION: ${{ secrets.GCP_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

  docker_build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: GCP Authenticate
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
      with:
        version: '>= 363.0.0'
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    #- name: Configure docker to use the gcloud cli
    #  run: gcloud auth configure-docker --quiet
    #- name: Build a docker image
      # run: docker build -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/payexecution_snapshot:${GITHUB_SHA::7} ./
    #  run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/payexecution_snapshot:${GITHUB_SHA::7} .

  docker_push:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1
    - name: GCP Authenticate
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@v1.1.0
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet
    - name: Build a docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/payexecution_snapshot:${GITHUB_SHA::7} .
    - name: Push the docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/payexecution_snapshot:${GITHUB_SHA::7} .

